#!/usr/bin/expect -f
set timeout -1

spawn scp -o StrictHostKeyChecking=no vamsi_crackers_admin_build.zip root@103.191.208.98:/var/www/vamsictackers/frontend/
expect "*assword:*"
send "Prasath@1990\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no root@103.191.208.98 "cd /var/www/vamsictackers/frontend/ && unzip -o vamsi_crackers_admin_build.zip && npm install && npm run build && pm2 restart all"
expect "*assword:*"
send "Prasath@1990\r"
expect eof
